// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SystemMVC.Models;

namespace SystemMVC.Migrations
{
    [DbContext(typeof(SystemContext))]
    [Migration("20210629062158_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SystemMVC.Models.Register", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email");

                    b.Property<string>("FirstName")
                        .HasColumnName("First_Name");

                    b.Property<string>("LastName")
                        .HasColumnName("Last_Name");

                    b.Property<string>("Mobile");

                    b.Property<string>("Password");

                    b.Property<string>("Phone");

                    b.Property<string>("UserName")
                        .HasColumnName("User_Name");

                    b.Property<int?>("UserType");

                    b.HasKey("Id");

                    b.ToTable("Register");
                });

            modelBuilder.Entity("SystemMVC.Models.Tasks", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("DeveloperName");

                    b.Property<string>("EndDate");

                    b.Property<string>("ImplentionName");

                    b.Property<string>("ModuleName");

                    b.Property<string>("TasKDesciption");

                    b.HasKey("Id");

                    b.ToTable("Tasks");
                });
#pragma warning restore 612, 618
        }
    }
}
